#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$REPO_DIR/competition/sweeps"
OUT_MD="$OUT_DIR/robustness_summary.md"
INCLUDE_COUPLED="${INCLUDE_COUPLED:-1}"

mkdir -p "$OUT_DIR"

"$REPO_DIR/scripts/sweep_synapse.sh"
"$REPO_DIR/scripts/sweep_lif_neuron.sh"
"$REPO_DIR/scripts/sweep_neuron_tile.sh"

if [[ "$INCLUDE_COUPLED" == "1" ]]; then
  "$REPO_DIR/scripts/sweep_neuro_tile4_coupled.sh"
fi

python3 - "$OUT_MD" "$OUT_DIR" "$INCLUDE_COUPLED" <<'PY'
import csv
import datetime as dt
import math
import sys
from pathlib import Path

out_md = Path(sys.argv[1])
out_dir = Path(sys.argv[2])
include_coupled = sys.argv[3] == "1"

entries = [
    ("Synapse", out_dir / "synapse_sweep.csv"),
    ("LIF Neuron", out_dir / "lif_neuron_sweep.csv"),
    ("Neuron Tile", out_dir / "neuron_tile_sweep.csv"),
]
if include_coupled:
    entries.append(("Neuro Tile4 Coupled", out_dir / "neuro_tile4_coupled_sweep.csv"))

def first_spike_values(rows):
    vals = []
    if not rows:
        return vals
    if "first_spike_ns" in rows[0]:
        for row in rows:
            try:
                vals.append(float(row["first_spike_ns"]))
            except Exception:
                pass
        return vals
    if "first_pulse_ns" in rows[0]:
        for row in rows:
            try:
                vals.append(float(row["first_pulse_ns"]))
            except Exception:
                pass
        return vals
    if "first_spike_times_ns" in rows[0]:
        for row in rows:
            raw = row.get("first_spike_times_ns", "").strip()
            if not raw:
                continue
            token = raw.split(",")[0].strip()
            try:
                vals.append(float(token))
            except Exception:
                pass
    return vals

def pass_counts(rows):
    if not rows:
        return (0, 0)
    if "overall_pass" in rows[0]:
        p = sum(1 for r in rows if r.get("overall_pass") == "PASS")
    elif "pass" in rows[0]:
        p = sum(1 for r in rows if r.get("pass") == "PASS")
    else:
        p = 0
    return (p, len(rows) - p)

lines = []
lines.append("# NeuroCore Robustness Sweep Summary")
lines.append("")
lines.append(f"Generated: {dt.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}")
lines.append("")
lines.append("| Block | Points | PASS | FAIL | First-spike range (ns) | CSV |")
lines.append("|-------|--------|------|------|-------------------------|-----|")

for name, csv_path in entries:
    if not csv_path.exists():
        lines.append(f"| {name} | 0 | 0 | 0 | n/a | `{csv_path}` (missing) |")
        continue
    rows = list(csv.DictReader(csv_path.open()))
    passed, failed = pass_counts(rows)
    first_vals = first_spike_values(rows)
    if first_vals:
        first_range = f"{min(first_vals):.3f} .. {max(first_vals):.3f}"
    else:
        first_range = "n/a"
    lines.append(
        f"| {name} | {len(rows)} | {passed} | {failed} | {first_range} | `{csv_path}` |"
    )

lines.append("")
lines.append("Generated by: `scripts/sweep_analog_robustness.sh`")

out_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY

echo "Robustness sweep bundle complete:"
echo "  summary: $OUT_MD"
