/*
###############################################################
#  Generated by:      Cadence Innovus 21.17-s075_1
#  OS:                Linux x86_64(Host ID vcl-vm0-159)
#  Generated on:      Mon Feb  2 14:34:14 2026
#  Design:            alu4_flow_demo
#  Command:           saveNetlist /home/v71349/analog-gradients/implementation/fullflow_demo/work/innovus/out/alu4_flow_demo_postroute.v
###############################################################
*/
module alu4_flow_demo (
	a, 
	b, 
	op, 
	y, 
	cout);
   input [3:0] a;
   input [3:0] b;
   input [1:0] op;
   output [3:0] y;
   output cout;

   // Internal wires
   wire n0;
   wire n1;
   wire n2;
   wire n3;
   wire c0;

   AND2X1 u_and0 (.Y(n0),
	.A(a[0]),
	.B(b[0]));
   AND2X1 u_and1 (.Y(n1),
	.A(a[1]),
	.B(b[1]));
   AND2X1 u_and2 (.Y(n2),
	.A(a[2]),
	.B(b[2]));
   AND2X1 u_and3 (.Y(n3),
	.A(a[3]),
	.B(b[3]));
   XOR2X1 u_xor0 (.Y(y[0]),
	.A(n0),
	.B(op[0]));
   XOR2X1 u_xor1 (.Y(y[1]),
	.A(n1),
	.B(op[0]));
   XOR2X1 u_xor2 (.Y(y[2]),
	.A(n2),
	.B(op[0]));
   XOR2X1 u_xor3 (.Y(y[3]),
	.A(n3),
	.B(op[0]));
   OR2X1 u_or0 (.Y(c0),
	.A(a[3]),
	.B(b[3]));
   XOR2X1 u_xor4 (.Y(cout),
	.A(c0),
	.B(op[1]));
endmodule

